Repository lisphilar/covid19-sir, pull requests merged in 2020-11, with the labels that each got.

#292 Issue290
  Pipfile
  covsirphy/__init__.py
  covsirphy/analysis/example_data.py
  covsirphy/analysis/model_validator.py
  covsirphy/cleaning/term.py
  covsirphy/ode/mbase.py
  covsirphy/ode/sewirf.py
  covsirphy/ode/sir.py
  covsirphy/ode/sird.py
  covsirphy/ode/sirf.py
  covsirphy/ode/sirfv.py
  covsirphy/phase/phase_estimator.py
  covsirphy/phase/phase_unit.py
  covsirphy/simulation/estimator.py
  covsirphy/simulation/simulator.py
  covsirphy/util/argument.py
  example/model_validation.py
  setup.cfg
  tests/test_ode.py
Labels: enhancement

#293 example: Greece (GRC)
  Pipfile
  example/scenario_analysis_grc.py
Labels: documentation

#294 example: update the length of future phase
  example/scenario_analysis_deu.py
  example/scenario_analysis_grc.py
  example/scenario_analysis_jpn.py
  example/scenario_analysis_usa.py
Labels: documentation

#295 example: fix argument of Scenario.add()
  example/scenario_analysis_deu.py
  example/scenario_analysis_grc.py
  example/scenario_analysis_jpn.py
  example/scenario_analysis_usa.py
Labels: bug, documentation

#297 fix: OverflowError in Scenario.retrospective()
  covsirphy/analysis/scenario.py
  covsirphy/simulation/estimator.py
Labels: bug

#298 docs: term definition
  Makefile
  docs/index.rst
  docs/markdown/TERM.md
Labels: documentation

#301 Refactoring dataloader
  covsirphy/__init__.py
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/country_data.py
  covsirphy/cleaning/covid19datahub.py
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/oxcgrt.py
  covsirphy/cleaning/population.py
  covsirphy/util/file.py
  docs/covsirphy.cleaning.rst
  tests/conftest.py
  tests/test_data_loader.py
  tests/test_dataloader.py
Labels: maintenance

#300 fix: trends curve fitting issue
  covsirphy/cleaning/term.py
  covsirphy/phase/sr_change.py
  covsirphy/phase/trend.py
Labels: bug

#302 refactoring
  covsirphy/phase/sr_change.py
  covsirphy/phase/trend.py
Labels: maintenance

#303 test: update for using linear function in trend
  covsirphy/phase/sr_change.py
  covsirphy/phase/trend.py
  tests/test_change_finder.py
  tests/test_phase_series.py
Labels: bug, maintenance

#304 Issue281 covid19datahub
  covsirphy/cleaning/covid19datahub.py
  covsirphy/cleaning/dataloader.py
  tests/test_dataloader.py
Labels: bug

#308 fix: wrong trends RMSLE conditions for selecting best dataframe
  covsirphy/phase/sr_change.py
  covsirphy/phase/trend.py
Labels: bug

#311 fix: reworked solution for trends analysis bug in Trend.run()
  covsirphy/phase/trend.py
Labels: bug

#314 move: Optimizer from simulation to util
  covsirphy/__init__.py
  covsirphy/simulation/estimator.py
  covsirphy/util/optimize.py
Labels: maintenance

#315 Refactoring for issue291
  covsirphy/phase/phase_estimator.py
  covsirphy/simulation/estimator.py
  covsirphy/util/stopwatch.py
Labels: maintenance

#316 docs
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/term.py
Labels: maintenance

#318 Create SECURITY.md
  SECURITY.md
Labels: Security, maintenance

#317 Issue269
  covsirphy/analysis/scenario.py
  tests/test_scenario.py
Labels: enhancement

#320 Issue319
  covsirphy/analysis/scenario.py
  example/scenario_analysis.py
  example/scenario_analysis_deu.py
  example/scenario_analysis_grc.py
  example/scenario_analysis_jpn.py
  example/scenario_analysis_usa.py
  tests/test_scenario.py
Labels: enhancement

#321 Issue291 rmsle
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/term.py
  covsirphy/ode/sirf.py
  covsirphy/simulation/estimator.py
  example/sewirf_model.py
  example/sir_model.py
  example/sird_model.py
  example/sirf_model.py
  example/sirfv_model.py
  tests/test_ode.py
  tests/test_policy_measures.py
  tests/test_scenario.py
Labels: bug, maintenance

#323 add: verbosity of data loading
  covsirphy/cleaning/covid19datahub.py
  covsirphy/cleaning/dataloader.py
Labels: enhancement

#324 update: stdout of DataLoader.jhu()
  covsirphy/cleaning/covid19datahub.py
Labels: bug

#325 fix: compatibility
  covsirphy/cleaning/covid19datahub.py
Labels: bug

#326 remove: imterpolation and sampling of S-R
  covsirphy/phase/sr_change.py
  tests/test_phase_series.py
  tests/test_phase_unit.py
  tests/test_policy_measures.py
  tests/test_scenario.py
Labels: bug

#327 update: default value of estimation timeout to 180
  covsirphy/simulation/estimator.py
Labels: bug, maintenance

#329 Issue328
  covsirphy/analysis/scenario.py
  tests/test_scenario.py
Labels: bug

#331 Issue330
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/term.py
  tests/test_ode.py
  tests/test_policy_measures.py
  tests/test_scenario.py
Labels: enhancement

#332 Issue291 model validator
  covsirphy/analysis/model_validator.py
  covsirphy/worldwide/policy.py
  tests/test_ode.py
  tests/test_policy_measures.py
  tests/test_scenario.py
Labels: maintenance

#333 Issue319 phases
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/term.py
  tests/test_scenario.py
Labels: enhancement

#336 support Python 3.6
  README.md
  docs/markdown/INSTALLATION.md
  setup.cfg
Labels: documentation, enhancement

#337 Issue319 past days
  covsirphy/analysis/scenario.py
  tests/test_scenario.py
Labels: enhancement

#338 Issue281 linelist
  Pipfile
  covsirphy/__init__.py
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/linelist.py
  example/load_linelist.py
  tests/test_dataloader.py
Labels: enhancement

#341 docs: citation of linelist
  docs/markdown/INSTALLATION.md
Labels: documentation

#342 example: Brazil scenario analysis
  Pipfile
  example/scenario_analysis_bra.py
Labels: documentation

#343 fix: JHUData._cleaning(), how to filling
  covsirphy/cleaning/jhu_data.py
Labels: bug

#344 Issue339 subset
  Makefile
  Pipfile
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/oxcgrt.py
  covsirphy/cleaning/population.py
  covsirphy/ode/sewirf.py
  covsirphy/ode/sir.py
  covsirphy/ode/sird.py
  covsirphy/ode/sirf.py
  covsirphy/ode/sirfv.py
  covsirphy/worldwide/policy.py
  setup.cfg
  tests/test_dataloader.py
Labels: bug

#345 fix: remove countries where R is 0 from list
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/worldwide/policy.py
Labels: bug

#346 example: for Netherlands
  Pipfile
  example/scenario_analysis_nld.py
Labels: documentation

#347 Issue334
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/jhu_data.py
  tests/test_dataloader.py
  tests/test_scenario.py
Labels: enhancement

#348 Issue339 refactor
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/country_data.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/oxcgrt.py
  covsirphy/cleaning/population.py
  covsirphy/cleaning/term.py
  example/usage_policy.ipynb
  tests/test_dataloader.py
  tests/test_ode.py
  tests/test_policy_measures.py
  tests/test_scenario.py
Labels: maintenance

#349 example: add UK scenario
  Pipfile
  example/scenario_analysis_gbr.py
Labels: maintenance

#350 fix: Na values in full complement
  covsirphy/cleaning/jhu_data.py
Labels: bug

#352 Issue351
  covsirphy/analysis/model_validator.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/term.py
  tests/test_dataloader.py
Labels: enhancement

#353 Issue340 use full
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/simulation/estimator.py
  covsirphy/worldwide/policy.py
  tests/test_dataloader.py
Labels: enhancement

#355 Issue354 separate class
  covsirphy/__init__.py
  covsirphy/analysis/param_tracker.py
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/term.py
  covsirphy/phase/phase_series.py
  example/usage_phases.ipynb
  tests/conftest.py
  tests/test_param_tracker.py
  tests/test_phase_series.py
  tests/test_scenario.py
Labels: maintenance

#358 Issue356
  Pipfile
  Pipfile.lock
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/jhu_data.py
  setup.cfg
  tests/test_dataloader.py
Labels: bug

#361 fix: LinelistData.subset()
  covsirphy/cleaning/linelist.py
  example/load_linelist.py
  tests/conftest.py
  tests/test_dataloader.py
Labels: bug

#365 test: remove linelist from conftest.py
  tests/conftest.py
  tests/test_dataloader.py
Labels: maintenance

#364 fix: sort recovery data + change linelist closed data to global
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/linelist.py
  example/load_linelist.py
  tests/test_dataloader.py
Labels: enhancement

#368 Test fixture
  tests/conftest.py
  tests/test_dataloader.py
  tests/test_param_tracker.py
  tests/test_scenario.py
Labels: maintenance

#369 Issue366
  covsirphy/cleaning/linelist.py
Labels: enhancement

#370 refactor: create JHUData.records()
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/jhu_data.py
  tests/test_dataloader.py
Labels: maintenance
