Repository lisphilar/covid19-sir, pull requests merged in 2020-12, with the labels that each got.

#371 add: Scenario.records_diff()
  covsirphy/analysis/scenario.py
  example/scenario_analysis.py
  tests/test_scenario.py
Labels: enhancement

#372 Issue367 datahandler
  covsirphy/__init__.py
  covsirphy/analysis/data_handler.py
  covsirphy/analysis/scenario.py
  tests/test_scenario.py
Labels: enhancement

#374 fix: ValueError in PolicyMeasures.estimate()
  covsirphy/phase/phase_estimator.py
  covsirphy/phase/sr_change.py
  covsirphy/worldwide/policy.py
  tests/test_policy_measures.py
Labels: bug

#375 add: SubsetNotFoundError
  covsirphy/__init__.py
  covsirphy/analysis/example_data.py
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/linelist.py
  covsirphy/cleaning/population.py
  covsirphy/util/error.py
Labels: enhancement

#376 add: ScenarioNotFoundError
  covsirphy/__init__.py
  covsirphy/analysis/param_tracker.py
  covsirphy/analysis/scenario.py
  covsirphy/util/error.py
Labels: enhancement, maintenance

#377 Issue359 fu tracker
  covsirphy/analysis/param_tracker.py
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/jhu_data.py
  tests/test_param_tracker.py
  tests/test_policy_measures.py
  tests/test_scenario.py
Labels: bug, maintenance

#378 Issue359 unexecuted
  covsirphy/__init__.py
  covsirphy/analysis/param_tracker.py
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/country_data.py
  covsirphy/cleaning/term.py
  covsirphy/phase/phase_unit.py
  covsirphy/util/error.py
  covsirphy/worldwide/policy.py
  tests/test_phase_unit.py
Labels: enhancement

#381 refactor
  covsirphy/cleaning/linelist.py
Labels: maintenance

#380 add: full complement when R >> I when outbreaking
  covsirphy/cleaning/jhu_data.py
  tests/test_dataloader.py
Labels: enhancement

#384 Issue357 recovery period
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/linelist.py
  tests/test_dataloader.py
Labels: enhancement

#385 Issue383 prefecture
  covsirphy/__init__.py
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/country_data.py
  covsirphy/cleaning/covid19datahub.py
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/japan_data.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/linelist.py
  covsirphy/cleaning/population.py
  tests/conftest.py
  tests/test_dataloader.py
Labels: enhancement

#386 add: DataLoader.jhu() calls .japan() internally
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/japan_data.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/linelist.py
  example/dataset_load.py
Labels: enhancement

#387 docs
  Makefile
  README.md
  docs/index.rst
  example/usage_dataset.ipynb
  example/usage_quick.ipynb
Labels: documentation

#388 update: dtypes of DataHandler.records_diff()
  covsirphy/analysis/data_handler.py
  example/usage_quick.ipynb
Labels: bug

#390 update: title of .records() when complement
  covsirphy/analysis/data_handler.py
  covsirphy/cleaning/jhu_data.py
Labels: enhancement

#391 add: JHUDataComplementHandler class
  covsirphy/__init__.py
  covsirphy/cleaning/jhu_complement.py
  covsirphy/cleaning/jhu_data.py
Labels: maintenance

#397 follow-up: no complement on example data
  covsirphy/analysis/example_data.py
  tests/test_dataloader.py
Labels: maintenance

#398 update: new line when may complement
  covsirphy/cleaning/jhu_complement.py
Labels: enhancement

#399 update: the output of ExampleData.records()
  covsirphy/analysis/example_data.py
Labels: maintenance

#400 update: title of Scenario.record_diff()
  covsirphy/analysis/data_handler.py
Labels: enhancement

#407 Issue389 fu
  covsirphy/__init__.py
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/japan_data.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/pcr_data.py
  covsirphy/cleaning/term.py
  covsirphy/util/error.py
  example/dataset_load.py
  example/usage_dataset.ipynb
  tests/conftest.py
  tests/test_datahub.py
  tests/test_dataloader.py
Labels: enhancement, maintenance

#408 Issue 404 406
  covsirphy/cleaning/country_data.py
  covsirphy/cleaning/jhu_data.py
  tests/test_datahub.py
  tests/test_dataloader.py
Labels: bug, enhancement

#409 Issue403 docs
  .github/CONTRIBUTING.md
  Makefile
  README.md
  docs/index.rst
  docs/markdown/INSTALLATION.md
  example/usage_dataset.ipynb
Labels: documentation

#410 supress: UserWarning in plotting
  covsirphy/simulation/estimator.py
Labels: bug

#412 Issue389 fu test
  covsirphy/__init__.py
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/covid19datahub.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/oxcgrt.py
  covsirphy/cleaning/pcr_data.py
  covsirphy/cleaning/population.py
  tests/test_datahub.py
Labels: maintenance

#413 docs: model description
  example/usage_theoretical.ipynb
Labels: documentation

#415 docs
  example/usage_theoretical.ipynb
Labels: documentation

#418 fix: DeprectionWarning with SIRFV
  covsirphy/ode/sirfv.py
Labels: bug

#419 docs: description of alpha1
  example/usage_theoretical.ipynb
Labels: documentation

#425 Issue421
  Pipfile
  covsirphy/cleaning/jhu_complement.py
  example/scenario_analysis_fra.py
  tests/test_datahub.py
Labels: bug, documentation

#428 improved full complement method + added _recovered_partial_ending()
  covsirphy/cleaning/jhu_complement.py
  covsirphy/cleaning/jhu_data.py
Labels: bug

#431 Issue430
  covsirphy/analysis/example_data.py
  covsirphy/cleaning/country_data.py
  covsirphy/cleaning/japan_data.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/linelist.py
  covsirphy/cleaning/oxcgrt.py
  covsirphy/cleaning/pcr_data.py
  covsirphy/cleaning/population.py
  covsirphy/cleaning/term.py
  covsirphy/phase/phase_series.py
  covsirphy/simulation/simulator.py
Labels: bug

#443 Issue442
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/linelist.py
Labels: bug

#439 fix in PCRData class: used min_pcr_tests
  covsirphy/cleaning/pcr_data.py
Labels: bug

#444 Issue422 rebase
  covsirphy/analysis/data_handler.py
  covsirphy/util/plotting.py
  tests/test_scenario.py
Labels: enhancement

#446 docs
  covsirphy/analysis/data_handler.py
Labels: documentation

#448 fu: accept Susceptible in Scenario.records()
  covsirphy/analysis/data_handler.py
  tests/test_scenario.py
Labels: bug

#447 Issue420
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/jhu_data.py
  tests/test_datahub.py
Labels: enhancement

#451 add: update PCRData with "Our World In Data"
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/pcr_data.py
  docs/markdown/INSTALLATION.md
  example/dataset_load.py
  tests/test_datahub.py
Labels: enhancement

#452 Issue429 vaccine
  covsirphy/__init__.py
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/term.py
  covsirphy/cleaning/vaccine_data.py
  docs/markdown/INSTALLATION.md
  example/dataset_load.py
  example/usage_dataset.ipynb
  tests/conftest.py
  tests/test_datahub.py
  tests/test_dataloader.py
Labels: New data loader, enhancement

#453 update: update control of PCRData
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/vaccine_data.py
  tests/test_dataloader.py
Labels: bug

#455 Issue429 pcr not default
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/pcr_data.py
  tests/test_datahub.py
Labels: bug

#460 test
  tests/test_dataloader.py
Labels: maintenance

#458 Issue429 pcr cumsum
  covsirphy/cleaning/pcr_data.py
  tests/test_datahub.py
Labels: bug, enhancement

#463 Issue449 raw3
  covsirphy/cleaning/linelist.py
  tests/test_dataloader.py
Labels: enhancement

#464 update: filling diff values in partial complement
  covsirphy/cleaning/jhu_complement.py
Labels: enhancement

#466 Use Single job starter workflow
  .semaphore/semaphore.yml
Labels: maintenance

#467 Issue56
  Makefile
  Pipfile
  Pipfile.lock
  covsirphy/__init__.py
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/pyramid.py
  docs/markdown/INSTALLATION.md
  example/dataset_load.py
  example/usage_dataset.ipynb
  setup.cfg
  tests/conftest.py
  tests/test_dataloader.py
Labels: enhancement

#468 revert: #464
  covsirphy/cleaning/jhu_complement.py
Labels: bug

#470 Issue445
  docs/markdown/TERM.md
  example/usage_dataset.ipynb
  example/usage_phases.ipynb
  example/usage_policy.ipynb
  example/usage_quick.ipynb
  example/usage_quickest.ipynb
  example/usage_theoretical.ipynb
Labels: documentation

#471 Issue280 prototype
  covsirphy/analysis/param_tracker.py
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/oxcgrt.py
  example/scenario_analysis_bra.py
  example/scenario_analysis_deu.py
  example/scenario_analysis_esp.py
  example/scenario_analysis_fra.py
  example/scenario_analysis_gbr.py
  example/scenario_analysis_grc.py
  example/scenario_analysis_jpn.py
  example/scenario_analysis_nld.py
  example/scenario_analysis_usa.py
  example/usage_quick.ipynb
  tests/test_param_tracker.py
  tests/test_scenario.py
Labels: enhancement

#476 Issue475
  covsirphy/cleaning/japan_data.py
  docs/markdown/INSTALLATION.md
  example/usage_dataset.ipynb
  tests/test_dataloader.py
Labels: New data loader, enhancement
