Repository lisphilar/covid19-sir, pull requests merged in 2020-10, with the labels that each got.

#245 Issue224
  covsirphy/analysis/scenario.py
  example/scenario_analysis.py
  example/scenario_analysis_jpn.py
  example/usage_quick.ipynb
  tests/test_scenario.py
Labels: enhancement

#249 update: use "Reproduction number", not "Rt"
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/term.py
Labels: bug

#251 Issue250
  covsirphy/analysis/scenario.py
  covsirphy/phase/phase_series.py
  covsirphy/phase/phase_unit.py
  example/scenario_analysis.py
  example/scenario_analysis_jpn.py
Labels: enhancement

#254 fix: error code of Scenario.add()
  covsirphy/analysis/scenario.py
Labels: bug

#258 Issue257
  covsirphy/worldwide/policy.py
  example/usage_policy.ipynb
  example/usage_quick.ipynb
  example/worldwide.py
  tests/test_policy_measures.py
Labels: bug

#259 fix: PolicyMeasures.param_history()
  covsirphy/worldwide/policy.py
Labels: bug

#263 fix: ValueError in PolicyMeasures.trend()
  covsirphy/worldwide/policy.py
Labels: bug

#265 fix: FileNotFoundError with dask.read_csv()
  Pipfile.lock
  covsirphy/cleaning/dataloader.py
Labels: bug

#277 docs: use COVID-19 Data Hub in Kaggle
  README.md
  docs/markdown/INSTALLATION.md
Labels: documentation

#278 config: download Kaggle datasets used in notebook
  input.py
Labels: bug, maintenance

#285 fix: max number of iteration, trend analysis
  covsirphy/phase/trend.py
Labels: bug

#286 fix: population-pyramid path in input.py script
  input.py
Labels: enhancement, maintenance

#287 update: title of simulation
  covsirphy/analysis/scenario.py
Labels: bug

#289 update: use sub-directories for kaggle datasets
  input.py
Labels: enhancement
