Repository lisphilar/covid19-sir, pull requests merged in 2021-01, with the labels that each got.

#482 Issue479
  .github/CONTRIBUTING.md
  .github/workflows/full_test.yml
  MANIFEST.in
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  covsirphy/cleaning/japan_data.py
  docs/markdown/INSTALLATION.md
  poetry.lock
  pyproject.toml
  setup.cfg
  setup.py
Labels: dependencies, documentation, enhancement, maintenance

#472 fix: partial and ending partial complement + show complement new method
  covsirphy/cleaning/jhu_complement.py
  covsirphy/cleaning/jhu_data.py
  tests/test_datahub.py
Labels: bug, enhancement

#485 Issue401 405 fu
  covsirphy/analysis/data_handler.py
  covsirphy/analysis/example_data.py
  covsirphy/analysis/model_validator.py
  covsirphy/analysis/param_tracker.py
  covsirphy/analysis/scenario.py
  covsirphy/cleaning/cbase.py
  covsirphy/cleaning/covid19datahub.py
  covsirphy/cleaning/dataloader.py
  covsirphy/cleaning/japan_data.py
  covsirphy/cleaning/jhu_complement.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/cleaning/pcr_data.py
  covsirphy/cleaning/population.py
  covsirphy/cleaning/term.py
  covsirphy/cleaning/vaccine_data.py
  covsirphy/phase/phase_estimator.py
  covsirphy/phase/phase_series.py
  covsirphy/phase/phase_unit.py
  covsirphy/phase/sr_change.py
  covsirphy/simulation/estimator.py
  covsirphy/simulation/simulator.py
  covsirphy/util/file.py
  covsirphy/util/optimize.py
  covsirphy/util/plotting.py
  covsirphy/worldwide/policy.py
  tests/test_datahub.py
Labels: maintenance

#489 fix: stricter condition in _recovered_partial()
  covsirphy/cleaning/jhu_complement.py
Labels: bug

#487 update: raise Error when failed in subsetting
  covsirphy/cleaning/jhu_complement.py
  covsirphy/cleaning/jhu_data.py
  covsirphy/util/error.py
  tests/test_datahub.py
Labels: enhancement

#536 docs: move usage_theoritical.ipynb to example dir
  example/usage_theoretical.ipynb
Labels: documentation

#541 [doc]: added recovery period term + show_complement() usage
  docs/markdown/TERM.md
  example/usage_dataset.ipynb
  example/usage_quick.ipynb
Labels: documentation

#571 test: update date range to accept change of raw
  tests/test_dataloader.py
Labels: maintenance
