Repository lisphilar/covid19-sir, pull requests merged in 2023-02, with the labels that each got.

#1351 close #1350
  covsirphy/gis/_layer.py
Labels: bug

#1297 Add Python 3.11 support
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  poetry.lock
  pyproject.toml
Labels: enhancement

#1357 [Docs] update the last year in citation, 2020-2022 to 2020-2023
  LICENSE
Labels: documentation

#1359 close #1358 by updating Monkey Pox data URL
  example/01_data_preparation.ipynb
Labels: documentation

#1366 update citation section of README
  README.md
Labels: documentation
